# Generated by Django 5.2.7 on 2025-10-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='resumes/')),
                ('text', models.TextField(blank=True)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
