# Generated by Django 5.2.7 on 2025-10-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='ResumeP',
        ),
    ]
