# Generated by Django 5.2.7 on 2025-10-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careera', '0003_resumecareer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumecareer',
            old_name='file',
            new_name='resume_file',
        ),
    ]
