# Generated by Django 5.2.7 on 2025-10-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careera', '0004_rename_file_resumecareer_resume_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeCareer',
        ),
    ]
